version: 4.0.0

global-settings:
  ethernet:
    access-mode: network-based

sil-kit:
  participant-name: CANoe4SW_SE
  config-file-path: ../SilKitConfig_CANoe.silkit.yaml

ethernet-networks:
  - name: tap_demo
    mapping: external-sil-kit

simulation-nodes:
  - name: SilKitDummyNode
    database-node: false
    network-assignments:
      - network: tap_demo
