#!/bin/bash
qemu-system-x86_64              \
  -m 2048M                                                \
  -smp 2                                                  \
  -boot c 	                                          \
  -nographic                                              \
  -serial mon:stdio\
  -nic user,hostfwd=tcp::10022-:22,mac=00:11:22:33:44:55  \
  -netdev tap,id=mynet0,ifname=qemu_demo_tap,script=no,downscript=no \
  -net nic,macaddr=52:54:56:53:4B:51,netdev=mynet0                      \
  -object filter-dump,id=tap_dump,netdev=mynet0,file=/tmp/qemu_linux_tap_dump \
  -hda silkit-qemu-demos-guest.qcow2
  
