name: trigger check for internal information
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call-check-info-workflow:
    uses: pnd/sil-kit-adapters-ci-testing/.github/workflows/check-internal-info.yaml@main
    with:
      repository_under_test : ${{ github.repository }}
      branch_under_test: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
